[tool.yapf]
based_on_style = "google"
align_closing_bracket_with_visual_indent = true
allow_multiline_lambdas = true
allow_multiline_dictionary_keys = false
allow_split_before_default_or_named_assigns = true
allow_split_before_dict_value = true
arithmetic_precedence_indication = false
blank_line_before_nested_class_or_def = false
blank_line_before_module_docstring = false
blank_line_before_class_docstring = false
blank_lines_around_top_level_definition = 1
blank_lines_between_top_level_imports_and_variables = 1
coalesce_brackets = false
column_limit = 100
continuation_align_style = "VALIGN_RIGHT"
continuation_indent_width = 1
dedent_closing_brackets = true
disable_ending_comma_heuristic = false
each_dict_entry_on_separate_line = true
force_multiline_dict = false
i18n_comment = ""
i18n_function_call = ""
indent_dictionary_value = true
indent_width = 1
indent_blank_lines = false
indent_closing_brackets = false
join_multiple_lines = false
no_spaces_around_selected_binary_operators = false
spaces_around_power_operator = true
spaces_around_default_or_named_assign = true
spaces_around_dict_delimiters = false
spaces_around_list_delimiters = false
spaces_around_subscript_colon = false
spaces_around_tuple_delimiters = false
spaces_before_comment = 1
space_between_ending_comma_and_closing_bracket = false
space_inside_brackets = false
split_arguments_when_comma_terminated = true
split_all_comma_separated_values = false
split_all_top_level_comma_separated_values = true
split_before_bitwise_operator = false
split_before_arithmetic_operator = false
split_before_closing_bracket = true
split_before_dict_set_generator = true
split_before_dot = true
split_before_expression_after_opening_paren = true
split_before_first_argument = true
split_before_logical_operator = false
split_before_named_assigns = true
split_complex_comprehension = false
split_penalty_after_opening_bracket = 10000
split_penalty_after_unary_operator = 0
split_penalty_arithmetic_operator = 0
split_penalty_before_if_expr = 0
split_penalty_bitwise_operator = 0
split_penalty_comprehension = 100000
split_penalty_excess_character = 0
split_penalty_for_added_line_split = 10000
split_penalty_import_names = 0
split_penalty_logical_operator = 0
use_tabs = true